# Generated by Django 5.1.4 on 2025-01-15 11:02

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50)),
                ('valid_from', models.DateField(default=app.models.default_valid_from)),
                ('expires_at', models.DateField(default=app.models.default_expires_at)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('date', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=3)),
                ('full_name', models.CharField(max_length=30)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.domain')),
            ],
        ),
    ]
