# Generated by Django 5.1.4 on 2025-01-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='card_last4',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
