# Generated by Django 5.1.4 on 2025-01-12 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_domain_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.DomainNameValidator()]),
        ),
    ]
